server:
  port: 8080
management:
  endpoint:
    metrics.enabled: true
    shutdown.enabled: true
  endpoints:
    web.exposure.include: metrics, health, info, httptrace, jolokia
    jmx.exposure.include: health

spring:
  redis:
    host: localhost
    port: 6379
    ssl: false
    cluster:
      enabled: false
    limit: 10000
